### ISSUE TITLE
Export as KML

### ISSUE THREAD

**Issue by tdooner** [hurricane-response/florence-api#1]
e.g. https://www.google.com/maps/d/u/0/viewer?mid=1FQti1xtzPgBu09WrvwMKlic5gwLgeKtL&ll=34.382028808154644%2C-78.8599227863478&z=8

**Comment by skorasaurus** [comment]
we're working on this at open cleveland

**Comment by skorasaurus** [comment]
https://docs.google.com/spreadsheets/d/1i0_xfYUKft0FoSOEkd2QtnonHyMhjwclp7rhOzGSjlg/edit#gid=0

**Comment by skorasaurus** [comment]
shuoldn't this be rephrased as exported as CSV ?

**Comment by skorasaurus** [comment]
what's left for loading [this list](https://www.google.com/maps/d/u/0/viewer?mid=1FQti1xtzPgBu09WrvwMKlic5gwLgeKtL&ll=34.382028808154644%2C-78.8599227863478&z=8) into https://hurricane-florence-api.herokuapp.com/shelters

https://github.com/hurricane-response/florence-api 

https://docs.google.com/spreadsheets/d/1i0_xfYUKft0FoSOEkd2QtnonHyMhjwclp7rhOzGSjlg/edit#gid=0

add a couple https://github.com/hurricane-response/florence-api

**Comment by DavidGinzberg** [comment]
Per @tdooner's help I believe we're done with this and ready to close the issue.

**Comment by miklb** [comment]
So is this issue resolved?

**Comment by skorasaurus** [comment]
yep.
