### ISSUE TITLE
API Search Box only returns county results

### ISSUE THREAD

**Issue by GovInTrenches** [hurricane-response/florence-api#10]
Expected behavior for the search bar would be to return any text that matches query (For example, Pittsboro) - instead it only returns county names. 

We need the search bar to search at the very least name, address, county

**Comment by nihonjinrxs** [comment]
All my testing, both locally and [in production](https://hurricane-florence-api.herokuapp.com/shelters) (top-right search field on the `/shelters` page) shows that all fields are included in search. `Pittsboro` seems not to be in the data, so I get no results for that particular search.

Am I looking in the right place? If not, can you provide a bit more information?

**Comment by GovInTrenches** [comment]
It seems to be working now - maybe something got updated? Or it take a bit to focus? 

Thanks for your help on this

**Comment by nihonjinrxs** [comment]
No worries. Glad it works!

**Comment by nihonjinrxs** [comment]
This can likely be closed, but I don't have permissions to do that.
