### ISSUE TITLE
Update instructions for Florence including calling script 

### ISSUE THREAD

**Issue by GovInTrenches** [hurricane-response/florence-api#2]
https://drive.google.com/file/d/0B4swUlBpdMTMQ25jYVZnSW1ZWG8/view <- this was a great guide; we should take it and update the site to show better instructions including a calling script

**Comment by Chrysaora** [comment]
I'm working on this here:
https://docs.google.com/document/d/15UYtfAmsGNLkYFyi4CdaIHQaN-YXRbhMbygN244qXiU/edit#

**Comment by GovInTrenches** [comment]
Done!
