### ISSUE TITLE
Feature Request: add POD (point of distribution)

### ISSUE THREAD

**Issue by miklb** [hurricane-response/florence-api#29]
I haven't investigated the schema to know if it would better to just add a new flag or create a whole new object.

cc @GovInTrenches

**Comment by GovInTrenches** [comment]
I’ve asked the fema Slack for a sample schema - will post back when they respond 

Christopher Whitaker
Code for America Brigade Manager
@CivicWhitaker

(Sent from mobile)

**Comment by miklb** [comment]
Fields Required:

- Facility Name
- Address
- City
- County
- Active For Event
