### ISSUE TITLE
Feature: add geoJSON endpoints

### ISSUE THREAD

**Issue by miklb** [hurricane-response/florence-api#44]
Mapbox GL ingests geojson nicely to allow more dynamic filtering and layering. 

If we had second API endpoints our mapipng options would open up.

I understand this is a longer term goal and needs more discussion but opening it up now after a day of reading the docs.

**Comment by nihonjinrxs** [comment]
Note: geojson spec is at https://tools.ietf.org/html/rfc7946#section-1.3
