### ISSUE TITLE
Feature: Delete Shelter in Admin UI

### ISSUE THREAD

**Issue by miklb** [hurricane-response/florence-api#54]
Currently I do not see an admin UI to delete a shelter. Only archive. Not sure what original design decision on that was.

**Comment by omnilord** [comment]
Looks like Destroy just wasn't coded for any of the resources.  The action is there, just empty.  A good idea for implementing this would be to add a "trash" table and insert any deleted rows into the trash table so if someone does delete a shelter that shouldn't be, we still have the record.
