### ISSUE TITLE
Predictive Dialer - update shelter info

### ISSUE THREAD

**Issue by ChrisTheDBA** [hurricane-response/florence-api#71]
Allow volunteers to request a set of shelters(phone) to update. Once they get their list, the numbers are taken off the stack. Update made - number released. No update made after 5 or 10 minutes, return to needs updating stack.

**Comment by miklb** [comment]
See also #15

**Comment by nihonjinrxs** [comment]
Closing this one as duplicate, as it's encompassed by discussion in #15.
