### ISSUE TITLE
Include Distribution Points in api:import for development environment

### ISSUE THREAD

**Issue by omnilord** [hurricane-response/florence-api#79]
@nihonjinrxs made an excellent observation that we don't have distribution points included in the api:import function and should add it.

Relevant files:
- [import.rake](https://github.com/hurricane-response/florence-api/blob/master/lib/tasks/import.rake)
- [api_importer.rb](https://github.com/hurricane-response/florence-api/blob/master/app/importers/api_importer.rb)
- New import job required (see import job scripts in [app/jobs](https://github.com/hurricane-response/florence-api/tree/master/app/jobs))

**Comment by miklb** [comment]
should we consider archived items in the API import as well?
