### ISSUE TITLE
Include archived items in the API import 

### ISSUE THREAD

**Issue by omnilord** [hurricane-response/florence-api#81]
_Originally posted by @miklb in https://github.com/hurricane-response/florence-api/issues/79#issuecomment-434527062_

**Comment by omnilord** [comment]
I've been thinking about how to include archived items without too much trouble.  I've drafted a solution in my repo but I still need to backfill updates to tests before I can PR an imports update.

There is a chicken/egg problem with the tests because the vcr cassettes are made from the api import process which has to hit the live API server in order to generate the vcr cassettes properly.  Opening this conversation with @nihonjinrxs about how to do this with Distribution Points as well.

**Comment by nihonjinrxs** [comment]
Per conversation in #80, for developer convenience features like this that don't impact production at all, I think tests are a nice-to-have, and may not be worth the time/effort.
