### ISSUE TITLE
Consider CFA Styleguide for admin interface

### ISSUE THREAD

**Issue by miklb** [hurricane-response/florence-api#88]
In [discussion about style guide](https://github.com/hurricane-response/response-theme/issues/2) for the map site, @tdooner brought this [CFA styleguide](https://cfa-styleguide.herokuapp.com/cfa/styleguide) to my attention and wonder if it might make a better admin UI for the API backend/call center.

**Comment by nihonjinrxs** [comment]
I think we've decided on this, so I'm going to close this decision one in favor of an "Implement this" one.
