### ISSUE TITLE
API Endpoint Filter for GeoCoordinates has an unused parameter

### ISSUE THREAD

**Issue by omnilord** [hurricane-response/florence-api#92]
On [Line 32](https://github.com/hurricane-response/florence-api/blob/master/app/controllers/concerns/filter_by_params.rb#L32) of the filter_by_params concern, the `:near` parameter is unused but is required for filtering by geocoordinates.  I believe the intent was to pass an _optional_ numeric value to the `#near` function on Line 35.

**Comment by devikanair** [comment]
Working on it from GHC with @D-Gould

**Comment by devikanair** [comment]
Per discussion on slack, this does not look like a problem and should be closed.
