### ISSUE TITLE
Bug: Can't unselect column sorting at '.../outdated' shelter table site

### ISSUE THREAD

**Issue by plocket** [hurricane-response/florence-api#94]
At https://api.hurricane-response.org/shelters/outdated you can select multiple columns to sort by, but you can't unselect any columns once you select them.

Refreshing the page (even without cache) doesn't unselect the columns.

[This isn't a problem at https://api.hurricane-response.org/shelters]

Browser: Chrome v75.0.3770.142

**Comment by nihonjinrxs** [comment]
The `/shelters/outdated` view is a sorted view (least recently updated first), so sorting should be disabled on that view. Will put in a new issue for that

**Comment by nihonjinrxs** [comment]
See issue #101
